swagger: '2.0'
info:
  title: AAAI Solutions API
  description: Direct API Gateway for AAAI Solutions
  version: 1.0.0
host: aaai-gateway-754x89jf.uc.gateway.dev
schemes:
  - https
produces:
  - application/json
paths:
  /auth/request-otp:
    post:
      summary: Request OTP for authentication
      operationId: requestOTP
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app/auth/request-otp
      responses:
        '200':
          description: OTP requested successfully
        '400':
          description: Bad request
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsRequestOTP
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app/auth/request-otp
      responses:
        '204':
          description: CORS preflight response
          
  /auth/verify-otp:
    post:
      summary: Verify OTP and get token
      operationId: verifyOTP
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app/auth/verify-otp
      responses:
        '200':
          description: OTP verified successfully
        '400':
          description: Bad request
        '401':
          description: Invalid OTP
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsVerifyOTP
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app/auth/verify-otp
      responses:
        '204':
          description: CORS preflight response
          
  /api/function/{function_name}:
    post:
      summary: Execute a function
      operationId: executeFunction
      parameters:
        - name: function_name
          in: path
          required: true
          type: string
          description: Name of the function to execute
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app/api/function/{function_name}
      security:
        - api_key: []
      responses:
        '200':
          description: Function executed successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Function not found
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsExecuteFunction
      parameters:
        - name: function_name
          in: path
          required: true
          type: string
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app/api/function/{function_name}
      responses:
        '204':
          description: CORS preflight response
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
    description: "Bearer token using HS256 JWT format"