swagger: '2.0'
info:
  title: AAAI Solutions JWT API with WebSocket Support
  description: JWT-based API Gateway for AAAI Solutions with Bearer token authentication and WebSocket routing
  version: 2.1.0
host: aaai-gateway-754x89jf.uc.gateway.dev
schemes:
  - https
  - wss
produces:
  - application/json
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: 'JWT Bearer token in the format: Bearer {jwt_token}'
x-google-endpoints:
  - name: aaai-gateway-754x89jf.uc.gateway.dev
    allowCors: true

# Enhanced CORS configuration for JWT with development support
responses:
  CorsResponse:
    description: Enhanced CORS response for JWT API with development support
    headers:
      Access-Control-Allow-Origin:
        type: string
        default: '*'
      Access-Control-Allow-Methods:
        type: string
        default: 'GET, POST, PUT, DELETE, OPTIONS, PATCH'
      Access-Control-Allow-Headers:
        type: string
        default: 'Content-Type, Authorization, X-Requested-With, Accept'
      Access-Control-Allow-Credentials:
        type: string
        default: 'true'
      Access-Control-Max-Age:
        type: string
        default: '3600'

paths:
  /auth/request-otp:
    post:
      summary: Request OTP for authentication
      operationId: requestOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/requestOTP
      responses:
        '200':
          description: OTP requested successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsRequestOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/requestOTP
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'
          
  /auth/verify-otp:
    post:
      summary: Verify OTP and get JWT tokens
      operationId: verifyOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/verifyOTP
      responses:
        '200':
          description: OTP verified, JWT tokens issued
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Invalid OTP
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsVerifyOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/verifyOTP
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'
          
  /api/function/{function_name}:
    post:
      summary: Execute a function with JWT authentication
      operationId: executeFunction
      parameters:
        - name: function_name
          in: path
          required: true
          type: string
          description: Name of the function to execute
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/executeFunction
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Function executed successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: JWT authentication failed
        '404':
          description: Function not found
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsExecuteFunction
      parameters:
        - name: function_name
          in: path
          required: true
          type: string
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/executeFunction
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /auth/refresh:
    post:
      summary: Refresh JWT access token using httpOnly refresh token
      operationId: refreshToken
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/refreshToken
      responses:
        '200':
          description: Token refreshed successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Invalid refresh token
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsRefreshToken
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/refreshToken
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /auth/logout:
    post:
      summary: Logout and revoke JWT tokens
      operationId: logout
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: JWT authentication failed
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsLogout
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/logout
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /ws/{user_id}:
    get:
      summary: WebSocket connection endpoint with JWT Bearer authentication
      operationId: websocketConnection
      parameters:
        - name: user_id
          in: path
          required: true
          type: string
          description: User ID for WebSocket connection
        - name: chat_id
          in: query
          required: false
          type: string
          description: Chat/Project ID for context
        - name: email
          in: query
          required: true
          type: string
          description: User email for validation
        - name: session_id
          in: query
          required: false
          type: string
          description: Session ID for tracking
        - name: auth_method
          in: query
          required: false
          type: string
          description: Authentication method identifier
      x-google-backend:
        address: wss://api-server-559730737995.us-central1.run.app
        protocol: websocket
      security:
        - bearerAuth: []
      responses:
        '101':
          description: WebSocket connection established
        '400':
          description: Bad request
        '401':
          description: JWT authentication failed
        '403':
          description: Access forbidden
        '404':
          description: User not found
        '500':
          description: Server error

  /api/chat:
    post:
      summary: Send chat message via HTTP with JWT authentication
      operationId: sendChatMessage
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Message sent successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: JWT authentication failed
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsChatMessage
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /api/chat/status/{message_id}:
    get:
      summary: Get chat message status with JWT authentication
      operationId: getChatMessageStatus
      parameters:
        - name: message_id
          in: path
          required: true
          type: string
          description: Message ID to check status
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Message status retrieved successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: JWT authentication failed
        '404':
          description: Message not found
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsChatMessageStatus
      parameters:
        - name: message_id
          in: path
          required: true
          type: string
      x-google-backend:
        address: https://api-server-559730737995.us-central1.run.app
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Access-Control-Allow-Methods:
              type: string
              default: 'GET, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'