swagger: '2.0'
info:
  title: AAAI Solutions API
  description: Direct API Gateway for AAAI Solutions with CORS support
  version: 1.0.0
host: aaai-gateway-754x89jf.uc.gateway.dev
schemes:
  - https
produces:
  - application/json
x-google-endpoints:
  - name: aaai-gateway-754x89jf.uc.gateway.dev
    allowCors: true
# Add global CORS configuration
responses:
  CorsResponse:
    description: Default CORS response
    headers:
      Access-Control-Allow-Origin:
        type: string
        default: 'https://aaai.solutions'
      Access-Control-Allow-Methods:
        type: string
        default: 'GET, POST, PUT, DELETE, OPTIONS'
      Access-Control-Allow-Headers:
        type: string
        default: 'Content-Type, Authorization, X-API-Key'
      Access-Control-Allow-Credentials:
        type: string
        default: 'true'
      Access-Control-Max-Age:
        type: string
        default: '3600'
paths:
  /auth/request-otp:
    post:
      summary: Request OTP for authentication
      operationId: requestOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/requestOTP
      responses:
        '200':
          description: OTP requested successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsRequestOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/requestOTP
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'
          
  /auth/verify-otp:
    post:
      summary: Verify OTP and get token
      operationId: verifyOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/verifyOTP
      responses:
        '200':
          description: OTP verified successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Invalid OTP
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsVerifyOTP
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/verifyOTP
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'
          
  /api/function/{function_name}:
    post:
      summary: Execute a function
      operationId: executeFunction
      parameters:
        - name: function_name
          in: path
          required: true
          type: string
          description: Name of the function to execute
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/executeFunction
      security:
        - api_key: []
      responses:
        '200':
          description: Function executed successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Function not found
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsExecuteFunction
      parameters:
        - name: function_name
          in: path
          required: true
          type: string
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/executeFunction
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization, X-API-Key'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /auth/validate-session:
    post:
      summary: Validate user session
      operationId: validateSession
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/validateSession
      security:
        - api_key: []
      responses:
        '200':
          description: Session validation successful
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsValidateSession
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/validateSession
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization, X-API-Key'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /auth/refresh:
    post:
      summary: Refresh access token using refresh token
      operationId: refreshToken
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/refreshToken
      responses:
        '200':
          description: Token refreshed successfully
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Invalid refresh token
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsRefreshToken
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/refreshToken
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /auth/refresh-silent:
    post:
      summary: Silent token refresh using cookies
      operationId: refreshTokenSilent
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/refreshTokenSilent
      responses:
        '200':
          description: Token refreshed silently
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Invalid refresh token
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsRefreshTokenSilent
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/refreshTokenSilent
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'

  /auth/logout:
    post:
      summary: Logout and invalidate tokens
      operationId: logout
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/logout
      security:
        - api_key: []
      responses:
        '200':
          description: Logout successful
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Server error
    options:
      summary: CORS support
      operationId: corsLogout
      x-google-backend:
        address: https://us-central1-aai-solutions-api-021201.cloudfunctions.net/logout
      responses:
        '204':
          description: CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: 'https://aaai.solutions'
            Access-Control-Allow-Methods:
              type: string
              default: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              type: string
              default: 'Content-Type, Authorization, X-API-Key'
            Access-Control-Allow-Credentials:
              type: string
              default: 'true'
            Access-Control-Max-Age:
              type: string
              default: '3600'